name: Create Component Dev Release

on:
  repository_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from specified branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch_name }}
      - name: Check current branch
        run: |
          git branch --show-current
          echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
          
      - name: Log Inputs
        run: |
          echo "Component Name: ${{ github.event.client_payload.source_repo }}"
          echo "Version: ${{ github.event.client_payload.existing_pr }}"
          echo "token: ${{ github.event.client_payload.pat_token }}"
          echo "pr_dev_tag" > ieg-addons-tag.txt
          RELEASE_TAG="ieg_0.0.381" # Example value
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV


      - name: Return RELEASE_TAG to Workflow A
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.NAVYA_GH_TOKEN }}
          repository: NAVYAGUPTA1403/ECommerce
          event-type: return-release-tag
          client-payload: '{"release_tag": "${{ env.RELEASE_TAG }}"}'
