name: Create Component Dev Release

on:
  repository_dispatch:
    types: [Trigger Workflow]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from specified branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.branch_name }}
          
      - name: Log Inputs
        run: |
          echo "Component Name: ${{ github.event.client_payload.source_repo }}"
          echo "Version: ${{ github.event.client_payload.existing_pr }}"
          echo "token: ${{ github.event.client_payload.pat_token }}"
          echo "pr_dev_tag" > ieg-addons-tag.txt
          echo "workspace: $GITHUB_WORKSPACE"
          echo "Done"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: output-artifact
            path: ../../
            if-no-files-found: error
