name: Create Component Dev Release

on:
  repository_dispatch:
    types: [Trigger Workflow]
    inputs:
      existing_pr:
        description: "PR Number"
        required: true
        default: "main"
      source_repo:
        description: "Source Repo for dev release"
        required: true
        type: string
      pat_token:
        description: "PAT token for auth"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: |
          echo "Component Name: ${{ github.event.client_payload.source_repo }}"
          echo "Version: ${{ github.event.client_payload.existing_pr }}"
          echo "token: ${{ github.event.client_payload.pat_token }}"
          echo "pr_dev_tag" > ieg-addons-tag.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
            name: output-artifact
            path: NAVYAGUPTA1403/ECommerce/ieg-addons-tag.txt
